services:
  - type: web
    name: piton-airflow
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""  # <-- important : désactive le build standard gunicorn
    startCommand: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --email admin@example.com --role Admin && (airflow webserver & airflow scheduler)"
    healthCheckPath: /health
    envVars:
      - key: AIRFLOW__CORE__EXECUTOR
        value: LocalExecutor
      - key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
        fromSecret: NEON_DB_CONN
      - key: AIRFLOW__CORE__FERNET_KEY
        generate: true
      - key: AIRFLOW__WEBSERVER__SECRET_KEY
        generate: true
      - key: AIRFLOW__WEBSERVER__WEB_SERVER_PORT
        value: "8080"
